# Generated by Django 5.0.4 on 2024-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='add',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
